project:
  type: website

website:
  title: "First Year Seminar 2025"
  favicon: emoji.png
  navbar:
    left:
      - href: index.qmd
        text: Home
      - schedule.qmd
      - assignments.md
      - policies.md

format:
  html:
    theme: vapor
    css: styles.css
    toc: true



